- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: IGN_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/emergency_room/model/mark1/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: IGN_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/mark1/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: IGN_TO_ROS

- ros_topic_name: "/odom"
  gz_topic_name: "/model/mark1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: IGN_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/world/emergency_room/model/mark1/link/base_footprint/sensor/pulsar_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: IGN_TO_ROS
  queue_size: 50

- ros_topic_name: "/depth_image"
  gz_topic_name: "/world/emergency_room/model/mark1/link/base_footprint/sensor/kinect_depth_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: IGN_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/mark1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_IGN