<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Orbbec Camera Properties (adjust dimensions based on your specific model) -->
    <xacro:property name="camera_length" value="0.088"/>
    <xacro:property name="camera_width" value="0.06"/>
    <xacro:property name="camera_height" value="0.06"/>
    <xacro:property name="camera_weight" value="0.32"/>

    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${camera_weight}" x="${camera_length}" y="${camera_width}" z="${camera_height}"
                         o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <!-- Camera Optical Frames -->
    <joint name="camera_color_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_color_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_color_frame"/>

    <joint name="camera_color_optical_joint" type="fixed">
        <parent link="camera_color_frame"/>
        <child link="camera_color_optical_frame"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_color_optical_frame"/>

    <joint name="camera_depth_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_depth_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
        <parent link="camera_depth_frame"/>
        <child link="camera_depth_optical_frame"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_depth_optical_frame"/>

    <!-- IMU Link -->
    <joint name="camera_imu_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_imu_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_imu_frame"/>

    <!-- Camera Mount Joint -->
    <joint name="pole_camera_joint" type="fixed">
        <parent link="pole_link"/>
        <child link="camera_link"/>
        <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0"/>
    </joint>
</robot>