<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.5"/>
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.6" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="caster_wheel_radius" value="0.04" />
    <xacro:property name="caster_wheel_width" value="0.025" />
    <xacro:property name="pole_length" value="0.6" />
    <xacro:property name="pole_radius" value="0.02" />
    <xacro:property name="gap_for_wheels" value="0.05" />
    <xacro:property name="gap_for_caster_wheels" value="${wheel_radius - (2*caster_wheel_radius)}" />

    <link name="base_footprint">
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/> 
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/> 
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="20" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="pole_link">
        <visual>
            <geometry>
                <cylinder radius="${pole_radius}" length="${pole_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${pole_radius}" length="${pole_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${pole_radius}" l="${pole_length}"
                                o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <!--<cylinder radius="${wheel_radius}" length="${wheel_width}"/>-->
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz = "0 0 0" rpy="${pi/2.0} 0 0" />
            </collision>
            <xacro:wheel_inertia m="0.2" r="${wheel_radius}" h="${wheel_width}"
                           o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0" />
        </link>
    </xacro:macro>

    
    <xacro:wheel_link prefix="rear_right" />
    <xacro:wheel_link prefix="rear_left" />

    <xacro:macro name="caster_wheel_link" params="prefix">

        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name="blue"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            </collision>

            <xacro:wheel_inertia m="0.05" r="${caster_wheel_radius}" h="${caster_wheel_width}"
                           o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:caster_wheel_link prefix="front_right" />
    <xacro:caster_wheel_link prefix="front_left" />

    <!-- <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint> -->

    <joint name="pole_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="pole_link"/>
        <origin xyz="0 0 ${base_height + base_height/2}" rpy="0 0 0"/>
    </joint>

    <!--front caster joints-->

    <joint name="front_left_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${(base_length/4) + (2*caster_wheel_radius)} ${(base_width/2)-(caster_wheel_width/2)} ${-(caster_wheel_radius+gap_for_caster_wheels)}" rpy="0 0 0"/>  
    </joint>

    <joint name="front_right_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${(base_length/4) + (2*caster_wheel_radius)} ${-((base_width/2)-(caster_wheel_width/2))} ${-(caster_wheel_radius+gap_for_caster_wheels)}" rpy="0 0 0"/>  
    </joint>

    <!--<joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${base_length/4} ${-((base_width/2)+(wheel_width/2))} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${base_length/4} ${(base_width/2)+(wheel_width/2)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>-->

    <joint name="base_rear_left_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="${-base_length/4} ${(base_width/2)+(wheel_width/2) + gap_for_wheels} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_rear_right_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="${-base_length/4} ${-((base_width/2)+(wheel_width/2)+gap_for_wheels)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
</robot>