<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Orbbec Camera Properties -->
    <xacro:property name="orbbec_camera_length" value="0.090"/>
    <xacro:property name="orbbec_camera_width" value="0.065"/>
    <xacro:property name="orbbec_camera_height" value="0.025"/>
    <xacro:property name="orbbec_camera_weight" value="0.3"/>

    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${orbbec_camera_length} ${orbbec_camera_width} ${orbbec_camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${orbbec_camera_length} ${orbbec_camera_width} ${orbbec_camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${orbbec_camera_weight}" x="${orbbec_camera_length}" y="${orbbec_camera_width}" z="${orbbec_camera_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <!-- Camera Depth Optical Frame -->
    <!-- <link name="camera_depth_optical_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_depth_optical_frame"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint> -->

    <!-- Camera RGB Optical Frame --> <!-- same is used for camera/depth/image_raw -->
    <link name="camera_color_optical_frame"/> <!-- same as hardware-->

    <joint name="camera_color_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_color_optical_frame"/>
        <!-- This orientation corrects for the optical frame convention -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    

    <!-- Camera IMU Link going to use just one linkf or sensors below the camera link
    <link name="camera_imu_link">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>-->

    <!-- <joint name="camera_imu_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> -->

    <!-- Camera IMU Optical Frame -->
    <!-- <link name="camera_imu_optical_frame"/> -->

    <!-- using real frames that hardware publishes-->
    <link name="camera_accel_gyro_optical_frame" />

    <joint name="camera_imu_optical_joint" type="fixed">
        <parent link="camera_link"/> <!-- removed extra link and added this directly to camera-->
        <!-- <child link="camera_imu_optical_frame"/> -->
        <child link="camera_accel_gyro_optical_frame" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <!-- this one is for camera IR-->
    <link name="camera_ir_optical_frame" />

    <joint name="camera_ir_optical_joint" type="fixed">
        <parent link="camera_link"/> 
        <!-- <child link="camera_imu_optical_frame"/> -->
        <child link="camera_ir_optical_frame" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <!-- Mount camera on pole -->
    <joint name="pole_camera_joint" type="fixed">
        <parent link="pole_link"/>
        <child link="camera_link"/>
        <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0"/>
    </joint>

</robot>